# Generated by Django 6.0 on 2025-12-19 18:24

from django.db import migrations


def create_ipagroup_contenttype(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.get_or_create(
        app_label='auth',
        model='ipagroup',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_settings_email_validation_template'),
        ('contenttypes', '0001_initial'),  # Ensure contenttypes is migrated first
    ]

    operations = [
        migrations.RunPython(create_ipagroup_contenttype),
    ]
