# Generated by Django 6.0 on 2025-12-21 00:00

from __future__ import annotations

from django.db import migrations


def create_ipauser_contenttype(apps, schema_editor) -> None:
    # The unmanaged IPAUser model is declared in core.models but uses
    # app_label="auth" so it appears in the default admin user location.
    # Django won't auto-create a ContentType row for unmanaged models.
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.get_or_create(
        app_label="auth",
        model="ipauser",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_ipagroup_contenttype"),
        ("contenttypes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_ipauser_contenttype),
    ]
