# Generated by Django 6.0 on 2025-12-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_organization_website_logo_urlfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeipapermissiongrant',
            options={'verbose_name': 'Permission Grant', 'verbose_name_plural': 'Permission Grants'},
        ),
    ]
