# Generated by Django 6.0 on 2025-12-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_membershiprequest_requested_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershiprequest',
            name='uniq_membershiprequest_open_user_type',
        ),
        migrations.RemoveConstraint(
            model_name='membershiprequest',
            name='uniq_membershiprequest_open_org_type',
        ),
        migrations.AddConstraint(
            model_name='membershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('requested_organization__isnull', True), ('status', 'pending'), models.Q(('requested_username', ''), _negated=True)), fields=('requested_username', 'membership_type'), name='uniq_membershiprequest_open_user_type'),
        ),
        migrations.AddConstraint(
            model_name='membershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('requested_organization__isnull', False), ('status', 'pending')), fields=('requested_organization', 'membership_type'), name='uniq_membershiprequest_open_org_type'),
        ),
    ]
