# Generated by Django 6.0 on 2025-12-28 17:41

import django.db.models.deletion
from django.db import migrations, models


def backfill_org_snapshots(apps, schema_editor) -> None:
    Organization = apps.get_model("core", "Organization")
    MembershipRequest = apps.get_model("core", "MembershipRequest")
    MembershipLog = apps.get_model("core", "MembershipLog")

    for req in (
        MembershipRequest.objects.exclude(requested_organization_id=None)
        .filter(requested_username="", requested_organization_code="")
        .iterator()
    ):
        org = Organization.objects.filter(pk=req.requested_organization_id).first()
        if org is None:
            continue
        req.requested_organization_code = org.code
        req.requested_organization_name = org.name
        req.save(update_fields=["requested_organization_code", "requested_organization_name"])

    for log in (
        MembershipLog.objects.exclude(target_organization_id=None)
        .filter(target_username="", target_organization_code="")
        .iterator()
    ):
        org = Organization.objects.filter(pk=log.target_organization_id).first()
        if org is None:
            continue
        log.target_organization_code = org.code
        log.target_organization_name = org.name
        log.save(update_fields=["target_organization_code", "target_organization_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_organization_sponsorship_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershiplog',
            name='chk_membershiplog_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='membershiprequest',
            name='chk_membershiprequest_exactly_one_target',
        ),
        migrations.AddField(
            model_name='membershiplog',
            name='target_organization_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membershiplog',
            name='target_organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='requested_organization_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='requested_organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(backfill_org_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='membershiplog',
            name='target_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_logs', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='requested_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_requests', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='membershiplog',
            index=models.Index(fields=['target_organization_code', 'created_at'], name='ml_org_code_at'),
        ),
        migrations.AddIndex(
            model_name='membershiplog',
            index=models.Index(fields=['target_organization_code', 'action', 'created_at'], name='ml_org_code_act_at'),
        ),
        migrations.AddIndex(
            model_name='membershiprequest',
            index=models.Index(fields=['requested_organization_code', 'status'], name='mr_org_code_status'),
        ),
        migrations.AddConstraint(
            model_name='membershiplog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_username', ''), models.Q(('target_organization__isnull', False), models.Q(('target_organization_code', ''), _negated=True), _connector='OR')), models.Q(models.Q(('target_username', ''), _negated=True), ('target_organization__isnull', True), ('target_organization_code', '')), _connector='OR'), name='chk_membershiplog_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='membershiprequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requested_organization__isnull', True), ('requested_organization_code', ''), models.Q(('requested_username', ''), _negated=True)), models.Q(('requested_username', ''), models.Q(('requested_organization__isnull', False), models.Q(('requested_organization_code', ''), _negated=True), _connector='OR')), _connector='OR'), name='chk_membershiprequest_exactly_one_target'),
        ),
    ]
