# Generated by Django 6.0 on 2025-12-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_organization_int_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCSVImportLink',
            fields=[
            ],
            options={
                'verbose_name': 'Membership import (CSV)',
                'verbose_name_plural': 'Membership import (CSV)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.membershiptype',),
        ),
    ]
