# Generated by Django 6.0 on 2025-12-29

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models

from core.migration_helpers.email_template_text import text_from_html


def create_membership_approval_templates(apps, schema_editor) -> None:
    EmailTemplate = apps.get_model("post_office", "EmailTemplate")
    MembershipType = apps.get_model("core", "MembershipType")

    # Add new templates here. Set assign=True to bind the template to the
    # membership type via MembershipType.acceptance_template.
    templates: list[dict[str, object]] = [
        {
            "name": "membership-request-approved-individual",
            "description": "Membership request approved (Individual)",
            "membership_type_code": "individual",
            "assign": True,
            "subject": "AlmaLinux OS Foundation Membership Application Approved",
            "html_content": (
                "<p>Hi there, {{ username }}!</p>\n"
                "<p>We are happy to share that your application for membership to the AlmaLinux OS Foundation as a member has been approved.</p>\n"
                "<p>We want to welcome you to the AlmaLinux OS Foundation and personally thank you for supporting our goals and mission. If you ever have any questions about AlmaLinux, or want to find out more ways you can get involved don't hesitate to ask as we always love a good discussion.</p>\n"
                "<p>If you are looking to increase your involvement in the community, there are a few different ways to do so! We have a <a href='https://wiki.almalinux.org/sigs/'>number of SIGs</a> that are actively working on all kinds of fun stuff, or you can help by answering questions"
                "  on the <a href='https://forums.almalinux.org'>forums</a> or <a href='https://www.reddit.com/r/AlmaLinux/'>reddit</a>.</p>\n"
                "\n<p><strong>Get connected</strong></p>\n"
                "<p>If you're not already, please join our chat server at <a href='https://chat.almalinux.org/'>chat.almalinux.org</a>. If you want to sport your very own AlmaLinux gear, head on over to <a href='https://shop.almalinux.org'>shop.almalinux.org</a> to pick up some goodies! We've got hoodies, shirts, mugs, phone cases and much more.</p>\n"
                "<p>Thanks again, and welcome to the AlmaLinux OS Foundation.</p>\n"
                "<p><em>The AlmaLinux Team</em></p>"
            ),
        },
        # Skeleton templates (fill these in later before applying migrations)
        {
            "name": "membership-request-approved-mirror",
            "description": "Membership request approved (Mirror)",
            "membership_type_code": "mirror",
            "assign": True,
            "subject": "AlmaLinux OS Foundation Mirror Sponsor Membership Approved",
            "html_content": (
                "<p>Hi there, {{ username }}!</p>\n"
                "<p>We are excited to welcome you as a Mirror sponsor member to the AlmaLinux OS Foundation, and I personally thank you for supporting our goals and mission. If you ever have any questions about AlmaLinux, or want to find out more ways you can get involved don't hesitate to ask as we always love a good discussion.</p>\n"
                "<p>Please join both the <a href='https://lists.almalinux.org/mailman3/lists/mirror.lists.almalinux.org/'>Mirrors</a> and the <a href='https://lists.almalinux.org/mailman3/lists/mirror-announce.lists.almalinux.org/'>Mirror-Announce</a> mailing lists to ensure that you get all the important information. If you're not already there, please join our chat server at <a href='https://chat.almalinux.org/'>chat.almalinux.org</a> - especially the ~mirrors and ~infrastructure channels.</p>\n"
                "<p>Thank you for backing the only enterprise Linux distribution built for the community, by the community. Your sponsorship will help us continue to build the infrastructure and operational needs of the foundation while building our reach and educating more people about how we can support them. We are very excited to have you.</p>\n"
                "\n<p><strong>Show it off!</strong></p>\n"
                "<p>If you want to sport your very own AlmaLinux gear, head on over to <a href='https://shop.almalinux.org'>shop.almalinux.org</a> to pick up some goodies! We have hoodies, shirts, mugs, phone cases, and much more.</p>\n"
                "<p>Thanks again, and welcome to the AlmaLinux OS Foundation.</p>\n"
                "<p><em>The AlmaLinux Team</em></p>"
            ),
        },
        {
            "name": "membership-request-approved-platinum",
            "description": "Membership request approved (Platinum Sponsor)",
            "membership_type_code": "platinum",
            "assign": True,
            "subject": "Welcome {{ organization_name }} as a Platinum Sponsor Member!",
            "html_content": (
                "<p>Hello!</p>\n"
                "<p>I am excited to welcome you as a Platinum sponsor member of the AlmaLinux OS Foundation. Your logo will be added to our website shortly, and will link to the URL that you provided in the application. We will send out an invoice for your sponsorship shortly!</p>\n"
                "<p>We'll also be reaching out soon to get a quote for your dedicated press release. Let us know if you aren't the right person for that, so we can streamline the process!</p>\n"
                "<p>Thank you for backing the only enterprise Linux distribution built for the community, by the community. Your sponsorship will help us continue to build infrastructure and pay for the operational needs of the foundation, while building our reach and educating more people about the ways that we can support them. We are very excited to have you.</p>\n"
                "\n<p><strong>Show it off!</strong></p>\n"
                "<p>If you haven't already, please join our chat server at <a href='https://chat.almalinux.org/'>chat.almalinux.org</a>. If you want to sport your very own AlmaLinux gear, head on over to <a href='https://shop.almalinux.org'>shop.almalinux.org</a> to pick up some goodies! We have hoodies, shirts, mugs, phone cases, and much more.</p>\n"
                "<p>Thanks again, and welcome to the AlmaLinux OS Foundation.</p>\n"
                "<p><em>The AlmaLinux Team</em></p>"
            ),
        },
        {
            "name": "membership-request-approved-gold",
            "description": "Membership request approved (Gold Sponsor)",
            "membership_type_code": "gold",
            "assign": True,
            "subject": "Welcome {{ organization_name }} as a Gold Sponsor Member!",
            "html_content": (
                "<p>Hello!</p>\n"
                "<p>I am excited to welcome you as a Gold sponsor member of the AlmaLinux OS Foundation. Your logo will be added to our website shortly, and will link to the URL that you provided in the application. We will send out an invoice for your sponsorship shortly!</p>\n"
                "<p>We'll also be reaching out soon to get a quote for our next Gold Sponsor press release. Let us know if you aren't the right person for that, so we can streamline the process!</p>\n"
                "<p>Thank you for backing the only enterprise Linux distribution built for the community, by the community. Your sponsorship will help us continue to build infrastructure and pay for the operational needs of the foundation, while building our reach and educating more people about the ways that we can support them. We are very excited to have you.</p>\n"
                "\n<p><strong>Show it off!</strong></p>\n"
                "<p>If you haven't already, please join our chat server at <a href='https://chat.almalinux.org/'>chat.almalinux.org</a>. If you want to sport your very own AlmaLinux gear, head on over to <a href='https://shop.almalinux.org'>shop.almalinux.org</a> to pick up some goodies! We have hoodies, shirts, mugs, phone cases, and much more.</p>\n"
                "<p>Thanks again, and welcome to the AlmaLinux OS Foundation.</p>\n"
                "<p><em>The AlmaLinux Team</em></p>"
            ),
        },
        {
            "name": "membership-request-approved-ruby",
            "description": "Membership request approved (Ruby Sponsor)",
            "membership_type_code": "ruby",
            "assign": True,
            "subject": "Welcome {{ organization_name }} as a Ruby Sponsor Member!",
            "html_content": (
                "<p>Hello!</p>\n"
                "<p>I am excited to welcome you as a Ruby sponsor member of the AlmaLinux OS Foundation. Your logo will be added to our website shortly, and will link to the URL that you provided in the application. We will send out an invoice for your sponsorship shortly!</p>\n"
                "<p>Thank you for backing the only enterprise Linux distribution built for the community, by the community. Your sponsorship will help us continue to build infrastructure and pay for the operational needs of the foundation, while building our reach and educating more people about the ways that we can support them. We are very excited to have you.</p>\n"
                "\n<p><strong>Show it off!</strong></p>\n"
                "<p>If you haven't already, please join our chat server at <a href='https://chat.almalinux.org/'>chat.almalinux.org</a>. If you want to sport your very own AlmaLinux gear, head on over to <a href='https://shop.almalinux.org'>shop.almalinux.org</a> to pick up some goodies! We have hoodies, shirts, mugs, phone cases, and much more.</p>\n"
                "<p>Thanks again, and welcome to the AlmaLinux OS Foundation.</p>\n"
                "<p><em>The AlmaLinux Team</em></p>"
            ),
        },
        {
            "name": "membership-request-approved-silver",
            "description": "Membership request approved (Silver Sponsor)",
            "membership_type_code": "silver",
            "assign": True,
            "subject": "Welcome {{ organization_name }} as a Silver Sponsor Member!",
            "html_content": (
                "<p>Hello!</p>\n"
                "<p>I am excited to welcome you as a Silver sponsor member of the AlmaLinux OS Foundation. Your logo will be added to our website shortly, and will link to the URL that you provided in the application. We will send out an invoice for your sponsorship shortly!</p>\n"
                "<p>Thank you for backing the only enterprise Linux distribution built for the community, by the community. Your sponsorship will help us continue to build infrastructure and pay for the operational needs of the foundation, while building our reach and educating more people about the ways that we can support them. We are very excited to have you.</p>\n"
                "\n<p><strong>Show it off!</strong></p>\n"
                "<p>If you haven't already, please join our chat server at <a href='https://chat.almalinux.org/'>chat.almalinux.org</a>. If you want to sport your very own AlmaLinux gear, head on over to <a href='https://shop.almalinux.org'>shop.almalinux.org</a> to pick up some goodies! We have hoodies, shirts, mugs, phone cases, and much more.</p>\n"
                "<p>Thanks again, and welcome to the AlmaLinux OS Foundation.</p>\n"
                "<p><em>The AlmaLinux Team</em></p>"
            ),
        },
    ]

    for spec in templates:
        name = str(spec["name"])
        subject = str(spec["subject"])
        html_content = str(spec["html_content"])
        content = text_from_html(html_content)

        tpl, _created = EmailTemplate.objects.update_or_create(
            name=name,
            language="",
            default_template=None,
            defaults={
                "subject": subject,
                "content": content,
                "html_content": html_content,
                "description": str(spec.get("description", "")),
            },
        )

        if not bool(spec.get("assign")):
            continue

        membership_type_code = str(spec["membership_type_code"])
        MembershipType.objects.filter(code=membership_type_code).update(acceptance_template_id=tpl.pk)


def noop_reverse(apps, schema_editor) -> None:
    # Keep templates and associations if migration is rolled back.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_membershipcsvimportlink"),
        ("post_office", "0013_email_recipient_delivery_status_alter_log_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="acceptance_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="post_office.emailtemplate",
                help_text="Email template used when a membership request is approved.",
            ),
        ),
        migrations.RunPython(create_membership_approval_templates, noop_reverse),
    ]
