# Generated by Django 6.0 on 2025-12-30 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_mailmerge_permission_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('number_of_seats', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('tallied', 'Tallied')], default='draft', max_length=16)),
                ('tally_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-start_datetime', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeipa_username', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('tiebreak_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.election')),
            ],
            options={
                'ordering': ('ordering', 'id'),
                'constraints': [models.UniqueConstraint(fields=('election', 'freeipa_username'), name='uniq_candidate_election_username')],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_public_id', models.CharField(db_index=True, max_length=128)),
                ('ranking', models.JSONField(blank=True, default=list)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('ballot_hash', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='core.election')),
            ],
            options={
                'indexes': [models.Index(fields=['election', 'created_at'], name='ballot_el_at')],
                'constraints': [models.UniqueConstraint(fields=('election', 'credential_public_id'), name='uniq_ballot_election_credential')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='core.election')),
            ],
            options={
                'ordering': ('timestamp', 'id'),
                'indexes': [models.Index(fields=['election', 'timestamp'], name='audit_el_ts'), models.Index(fields=['election', 'is_public'], name='audit_el_pub')],
            },
        ),
        migrations.CreateModel(
            name='VotingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('freeipa_username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.election')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('freeipa_username__isnull', False)), fields=('election', 'freeipa_username'), name='uniq_credential_election_username')],
            },
        ),
    ]
